### PR TITLE
Fix the issue with `syncGJAccountNew`

### PR DESCRIPTION
**Pull request by ContentGamer**
The last server url of `syncGJAccountNew` doesn't work (aka http://www.robtopgames.org), so I fixed it, the fixed url is http://www.boomlings.com

### CODE REVIEW

**Comment by Wyliemaster** [comment]
This will need investigating before I can merge. If possible, could you show some requests of the endpoint in action?

Make sure to censor the sensitive information if you choose to do so

Regardless, it will be checked in due time

**Comment by A-Zalt** [comment]
Don't forget that the GD client uses https since 2.2

**Comment by ContentGamer** [comment]
@A-Zalt The previous database url doesn't work, it sends one of these responses

-1 or -11

And yes, the fields were "accountID" and "gjp2" (hashed password) and secret.

But the boomlings one is the only one that i tried and works, does anyone have this issue?

**Comment by ContentGamer** [comment]
@A-Zalt Hm, I should try that.

**Comment by ContentGamer** [comment]
@A-Zalt this is the result with **http**://www.robtopgames.org

Screenshot from 2024-07-18 12-31-12
Screenshot from 2024-07-18 12-34-19

@A-Zalt  this is the result with **https**://www.robtopgames.org

Screenshot from 2024-07-18 12-36-11

@Wyliemaster this is the result with **http**://www.boomlings.com

Screenshot from 2024-07-18 12-40-52
Screenshot from 2024-07-18 12-41-47

**Pull request closed without merging**
